export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const ADD_TO_TOTAL_PRICE = "ADD_TO_TOTAL_PRICE";
export const SET_INITIAL_TOTAL_PRICE = "SET_INITIAL_TOTAL_PRICE";
export const SUBTRACT_FROM_TOTAL__PRICE = "SUBTRACT_FROM_TOTAL__PRICE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const FETCH_INGREDIENTS_SUCCEEDED = "FETCH_INGREDIENTS_SUCCEEDED";

export const PURCHASE_BURGER_SUCCEEDED = "PURCHASE_BURGER_SUCCEEDED";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const START_PURCHASING_BURGER = "START_PURCHASING_BURGER";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_SUCCEEDED = "FETCH_ORDERS_SUCCEEDED";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCEEDED = "AUTH_SUCCEEDED";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
