export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_TO_TOTAL_PRICE = "ADD_TO_TOTAL_PRICE";
export const SUBTRACT_FROM_TOTAL__PRICE = "SUBTRACT_FROM_TOTAL__PRICE";
